version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/rails:cached
      - bundle:/usr/local/bundle
    environment:
      RAILS_ENV: development
      NODE_ENV: development
      WEB_CONCURRENCY: 0
      VITE_RUBY_HOST: "0.0.0.0"
    ports:
      - "3000:3000"
      - "3036:3036"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  bundle:
